name: Benchmark

on:
  workflow_dispatch:

env:
  GTEST_VER: 1.14.0

jobs:
  benchmark:
    name: benchmark
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build linux package for x86_64
        run: |
          docker build -t cpplint ./
          docker run --name cpplint cpplint
          docker cp cpplint:/cpplint-cpp/dist ./
          docker cp cpplint:/cpplint-cpp/subprojects ./

      - name: Copy gooletest, Download cpplint.py
        run: |
          cp -r subprojects/googletest-${{ env.GTEST_VER }} ../
          curl -O https://raw.githubusercontent.com/cpplint/cpplint/ab7335bcc734f6d21226631060888bfb77bbc9d7/cpplint.py

      - name: Show CPU info
        run: |
          lscpu
          ./dist/cpplint-cpp --threads=

      - name: Lint cpplint-cpp
        run: |
          python benchmark.py . --cpplint_cpp="./dist/cpplint-cpp"
          sh memory_usage.sh "python cpplint.py" .
          sh memory_usage.sh "./dist/cpplint-cpp" .

      - name: Lint googletest
        run: |
          python benchmark.py ../googletest-${{ env.GTEST_VER }} --cpplint_cpp="./dist/cpplint-cpp"
          sh memory_usage.sh "python cpplint.py" ../googletest-${{ env.GTEST_VER }}
          sh memory_usage.sh "./dist/cpplint-cpp" ../googletest-${{ env.GTEST_VER }}
